[platformio]
src_dir = V2.0

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -Os
lib_deps =
  olikraus/U8g2
  makuna/Rtc
  adafruit/Adafruit ADS1X15
