[platformio]
src_dir = V2.0
packages_dir = .pio/packages

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.3.9/esp32-core-3.3.9.tar.xz
monitor_speed = 115200
board_build.partitions = ota_nofs_4MB.csv
build_flags = -Os
lib_deps =
  olikraus/U8g2
  makuna/Rtc
  adafruit/Adafruit ADS1X15
